# Generated by Django 5.0.6 on 2024-06-26 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_fan_fixture_mood_new_squad_team_results_standing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fan')),
            ],
        ),
    ]
