# Generated by Django 5.0.6 on 2024-06-29 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_comment_fann'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='fann',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.fan'),
        ),
    ]
