# Generated by Django 5.0.6 on 2024-06-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_comment_fann'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
