# Generated by Django 5.0.6 on 2024-06-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='fann',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
