# Generated by Django 5.0.6 on 2024-06-29 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
