# Generated by Django 5.0.6 on 2024-06-29 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('fann', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fan')),
            ],
        ),
    ]
