# Generated by Django 5.0.6 on 2024-07-01 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='fan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.fan'),
        ),
    ]
