# Generated by Django 5.0.6 on 2024-07-02 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_message_fan_delete_mood_remove_comment_fann_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='fann',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.fan'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fan')),
            ],
        ),
    ]
