# Generated by Django 5.0.6 on 2024-07-08 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_mood_remove_comment_user_comment_fann_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
