# Generated by Django 4.2.11 on 2024-05-03 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MouseClub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squad',
            old_name='secondtname',
            new_name='secondname',
        ),
    ]
