# Generated by Django 4.2.11 on 2024-05-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MouseClub', '0002_rename_secondtname_squad_secondname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squad',
            old_name='lasttname',
            new_name='lastname',
        ),
        migrations.RemoveField(
            model_name='squad',
            name='secondname',
        ),
    ]
