# Generated by Django 4.2.11 on 2024-05-09 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MouseClub', '0004_fixture_team_standing_results_fixture_home_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='away_team',
        ),
    ]
