# Generated by Django 4.2.11 on 2024-05-09 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MouseClub', '0005_remove_fixture_away_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixture', to='MouseClub.team'),
        ),
    ]
