# Generated by Django 4.2.11 on 2024-05-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MouseClub', '0010_alter_results_fixture'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='attacking',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='squad',
            name='defending',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='squad',
            name='dribbling',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='squad',
            name='shoot',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='squad',
            name='skills',
            field=models.IntegerField(null=True),
        ),
    ]
