# Generated by Django 4.2.11 on 2024-05-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MouseClub', '0013_new'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standing',
            options={'ordering': ['points', 'goals']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-name']},
        ),
        migrations.AddField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
